/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExamCalifUnidad;

import PuntoDeVenta.*;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jmanu
 */
public class VentProm extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public VentProm() {
        initComponents();
        modelo=(DefaultTableModel) tblProd.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblProducto = new javax.swing.JLabel();
        lblCant = new javax.swing.JLabel();
        cmbUni = new javax.swing.JComboBox<>();
        txtCalif = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProd = new javax.swing.JTable();
        lblSub2 = new javax.swing.JLabel();
        txtProm = new javax.swing.JTextField();
        rbtnOrd = new javax.swing.JRadioButton();
        rbtnRev = new javax.swing.JRadioButton();
        rbtNiv = new javax.swing.JRadioButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProducto.setText("Unidad");

        lblCant.setText("Calif");

        cmbUni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Producto", "1 ", "2 ", "3 ", "4 ", "5 ", "6 " }));
        cmbUni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbUniMouseClicked(evt);
            }
        });
        cmbUni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbUniKeyReleased(evt);
            }
        });

        txtCalif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCalifKeyReleased(evt);
            }
        });

        tblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Unidad", "Ordinario", "Revaluacion", "Niv"
            }
        ));
        tblProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblProdMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblProd);

        lblSub2.setText("Total");

        txtProm.setEditable(false);
        txtProm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPromActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnOrd);
        rbtnOrd.setSelected(true);
        rbtnOrd.setText("Ord");
        rbtnOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOrdActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnRev);
        rbtnRev.setText("Rev");
        rbtnRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRevActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtNiv);
        rbtNiv.setText("Niv");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSub2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProm, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(11, 11, 11))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProducto)
                                    .addComponent(lblCant))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbUni, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCalif, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rbtnOrd)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnRev)
                                .addGap(18, 18, 18)
                                .addComponent(rbtNiv))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnAgregar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(cmbUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCant)
                    .addComponent(txtCalif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnOrd)
                    .addComponent(rbtnRev)
                    .addComponent(rbtNiv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSub2)
                    .addComponent(txtProm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCalifKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalifKeyReleased

    }//GEN-LAST:event_txtCalifKeyReleased

    private void cmbUniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbUniMouseClicked

    }//GEN-LAST:event_cmbUniMouseClicked

    private void cmbUniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbUniKeyReleased

    }//GEN-LAST:event_cmbUniKeyReleased

    private void txtPromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPromActionPerformed

    private void tblProdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdMousePressed
        
    }//GEN-LAST:event_tblProdMousePressed

    private void tblProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdMouseClicked
        if (evt.getButton()==3) {
            if (showConfirmDialog(this, "Eliminar")==0) {
                modelo.removeRow(tblProd.getSelectedRow());
            }
            
        }
    }//GEN-LAST:event_tblProdMouseClicked
    public void validarcalif() throws ExamException{
        int a=Integer.parseInt(txtCalif.getText());
        if (rbtnOrd.isSelected()) {
            if (a>=70&&a<=100||a==0) {
                O[1]=txtCalif.getText();
                O[2]=" ";
                O[3]=" ";
                st=st+Integer.parseInt(txtCalif.getText());
            }else{
                throw new ExamException("Escriba un numero valido");
            }
        }else{
            if(rbtnRev.isSelected()){
                if (a>=70&&a<=90||a==0) {
                    O[1]=" ";
                    O[2]=txtCalif.getText();
                    O[3]=" ";
                    st=st+Integer.parseInt(txtCalif.getText());
                }else{
                    throw new ExamException("Escriba un numero valido");
                }
            }else{
                if (a>=70&&a<=80||a==0) {
                    O[1]=" ";
                    O[3]=txtCalif.getText();
                    O[2]=" ";
                    st=st+Integer.parseInt(txtCalif.getText());
                }else{
                    throw new ExamException("Escriba un numero valido");
                }
            }
        }
        
   }
    private void rbtnOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOrdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbtnOrdActionPerformed

    private void rbtnRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnRevActionPerformed
    public boolean ncalf()throws ExamException{
        if (tblProd.getRowCount()<=6) {
            return true;
        }else{
            throw new ExamException("No se puede agregar mas");
        }
    }
    public void validunid()throws ExamException{
        int temp[]=new int[6];
        for (int i = 0; i < tblProd.getRowCount(); i++) {
            int val=Integer.parseInt((String)modelo.getValueAt(i, 0));
            temp[i]=val;
            
                if (temp[i]==cmbUni.getSelectedIndex()) {
                    throw new ExamException("No se puede agregar otra vez");
                }
            
            
        }
    }
    public void selUni()throws ExamException{
        if (cmbUni.getSelectedIndex()==0) {
            throw new ExamException("Escoja una unidad");
        }
        
    }
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            // TODO add your handling code here:
            if (ncalf()) {
                selUni();
                String cad=(String) cmbUni.getSelectedItem();
                String A[]=cad.split(" ");
                validarcalif();
                validunid();
                O[0]=A[0];
                modelo.addRow(O);
                float prom=st/6;
                txtProm.setText(prom+" ");
            }
            
        } catch (ExamException ex) {
            showMessageDialog(rootPane, ex);
        }
            
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentProm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentProm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentProm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentProm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentProm().setVisible(true);
            }
        });
    }
    private DefaultTableModel modelo;
    private float st=0,b=0;
    public String B[],z,x,y;
    public Object O[]=new Object[4];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbUni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCant;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblSub2;
    private javax.swing.JRadioButton rbtNiv;
    private javax.swing.JRadioButton rbtnOrd;
    private javax.swing.JRadioButton rbtnRev;
    private javax.swing.JTable tblProd;
    private javax.swing.JTextField txtCalif;
    private javax.swing.JTextField txtProm;
    // End of variables declaration//GEN-END:variables
}
