/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExamenCancion;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jmanu
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbArt = new javax.swing.JComboBox<>();
        cmbCan = new javax.swing.JComboBox<>();
        btnCom = new javax.swing.JButton();
        btnLim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMusi = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Artista");

        jLabel2.setText("Canciones");

        cmbArt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Artista 1", "Artista 2", "Artista 3", "Artista 4" }));
        cmbArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbArtActionPerformed(evt);
            }
        });

        cmbCan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artista 1", "Artista 2", "Artista 3", "Artista 4", " " }));

        btnCom.setText("jButton1");
        btnCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComActionPerformed(evt);
            }
        });

        btnLim.setText("jButton2");

        tblMusi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cancion", "Artista", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tblMusi);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnCom)
                                    .addGap(125, 125, 125)
                                    .addComponent(btnLim))))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCom)
                    .addComponent(btnLim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbArtActionPerformed
        // TODO add your handling code here:
        if (cmbArt.getSelectedIndex()==1) {
            cmbCan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CancionA1 1", "CancionA1 2", "CancionA1 3", "CancionA1 4" }));
            for (int i = 0; i < 4; i++) {
                Precio[1][i]=(int)(Math.random()*10);
                
            }
        }else{
            if (cmbArt.getSelectedIndex()==2) {
                cmbCan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CancionA2 1", "CancionA2 2", "CancionA2 3", "CancionA2 4" }));
                for (int i = 0; i < 4; i++) {
                Precio[2][i]=(int)(Math.random()*10);
                
                }
            } else {
                if (cmbArt.getSelectedIndex()==3) {
                cmbCan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CancionA2 1", "CancionA2 2", "CancionA2 3", "CancionA2 4" }));
                for (int i = 0; i < 4; i++) {
                    Precio[3][i]=(int)(Math.random()*10);
                }
                }else{
                    if (cmbArt.getSelectedIndex()==4) {
                        cmbCan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CancionA2 1", "CancionA2 2", "CancionA2 3", "CancionA2 4" }));
                        for (int i = 0; i < 4; i++) {
                            Precio[4][i]=(int)(Math.random()*10);
                
                        }
                    }
                }
            }
        }
        
    }//GEN-LAST:event_cmbArtActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComActionPerformed
            Object O[]=new Object[3];
            int cant=Precio[cmbArt.getSelectedIndex()][cmbCan.getSelectedIndex()];
            O[0]=(String)cmbCan.getSelectedItem()+"";
            O[1]=(String)cmbArt.getSelectedItem()+"";
            O[2]=(Object)cant;
            modelo.addRow(O);

            cmbArt.setSelectedIndex(0);
            cmbArt.requestFocus();
            total=total+cant;
    }//GEN-LAST:event_btnComActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    private DefaultTableModel modelo;
    private int total=0;
    public int Precio[][]=new int[4][4];
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCom;
    private javax.swing.JButton btnLim;
    private javax.swing.JComboBox<String> cmbArt;
    private javax.swing.JComboBox<String> cmbCan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblMusi;
    // End of variables declaration//GEN-END:variables
}
