/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Curp;

import javax.swing.JOptionPane;

/**
 *
 * @author jmanu
 */
public class VentCurp extends javax.swing.JFrame {

    /**
     * Creates new form VentCurp
     */
    public VentCurp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPat = new javax.swing.JTextField();
        txtMat = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        dateNac = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        cboxFech = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtCurp = new javax.swing.JTextField();
        btnGen = new javax.swing.JButton();
        btnSal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rbtnHom = new javax.swing.JRadioButton();
        rbtnMuj = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Paterno");

        jLabel2.setText("A. Materno");

        jLabel3.setText("Nombres");

        jLabel4.setText("Fecha Nac.");

        dateNac.setDateFormatString("dd/MM/yyyy");
        dateNac.setMinimumSize(new java.awt.Dimension(50, 35));
        dateNac.setPreferredSize(new java.awt.Dimension(120, 20));

        jLabel6.setText("Sexo");

        cboxFech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Estado", "Nayarit", "Jalisco", "Mexico", "Michoacan" }));

        jLabel7.setText("Curp");

        btnGen.setText("Generar");
        btnGen.setPreferredSize(new java.awt.Dimension(80, 32));
        btnGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenActionPerformed(evt);
            }
        });

        btnSal.setText("Salir");
        btnSal.setMinimumSize(new java.awt.Dimension(80, 32));
        btnSal.setPreferredSize(new java.awt.Dimension(60, 32));

        jLabel8.setText("Entidad Fed.");

        buttonGroup1.add(rbtnHom);
        rbtnHom.setText("Hombre");
        rbtnHom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnHomActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnMuj);
        rbtnMuj.setText("Mujer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboxFech, 0, 150, Short.MAX_VALUE)
                                    .addComponent(txtCurp)
                                    .addComponent(txtMat)
                                    .addComponent(txtNom)
                                    .addComponent(txtPat))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbtnHom)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbtnMuj))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboxFech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbtnHom)
                    .addComponent(rbtnMuj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String getpLpV(String cad)throws CurpException{
        cad=cad.toUpperCase();
        String pl="",voc="AEIOU";
        if (cad.equals("")){
            throw new CurpException("Cadena Vacia");   
        }
        pl=cad.substring(0,1);
        for (int i = 1; i < cad.length(); i++) {
            if (voc.indexOf(cad.substring(i,i+1))!=1) {
                pl=pl+cad.substring(i, i+1);
                break;
            }            
        }
        return pl;
    }
    public String getpC(String cad)throws CurpException{
        cad=cad.toUpperCase();
        String pl="",voc="AEIOU";
        if (cad.equals("")){
            throw new CurpException("Cadena Vacia");   
        }
        for (int i = 2; i < cad.length(); i++) {
            if (voc.indexOf(cad.substring(i,i+1))==1) {
                pl=pl+cad.substring(i, i+1);
                break;
            }            
        }
        return pl;
    }

    public String cambCad(String cad){
        String pa[]={"PENE","PUTO","PUTA","LOCO","CACA"};
        for (int i = 0; i < pa.length; i++) {
            if(cad.equals(pa[i])){
                cad=cad.substring(0, 1)+"X"+cad.substring(2, 4);
            }   
        }
        return cad;
    }
    public String getpL(String cad)throws CurpException{
        cad=cad.toUpperCase();
        String pl="";
        if (cad.equals("")){
            throw new CurpException("Cadena Vacia");   
        }
        pl=cad.substring(0,1);
        return pl;
    }
    private void rbtnHomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnHomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnHomActionPerformed

    private void btnGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenActionPerformed
        String Curp=" ";
        try {
            Curp=getpLpV(txtPat.getText());
            Curp=Curp+getpL(txtMat.getText())+getpL(txtNom.getText());
            Curp=cambCad(Curp);
        } catch (CurpException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        txtCurp.setText(Curp);
    }//GEN-LAST:event_btnGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentCurp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentCurp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGen;
    private javax.swing.JButton btnSal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboxFech;
    private com.toedter.calendar.JDateChooser dateNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rbtnHom;
    private javax.swing.JRadioButton rbtnMuj;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtMat;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPat;
    // End of variables declaration//GEN-END:variables
}
