/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Complejo;
import static javax.swing.JOptionPane.*;
import static proyectos_tec.EjerciciosU3.*;
/**
 *
 * @author jmanu
 */
public class VentanaComplex extends javax.swing.JFrame {

    /**
     * Creates new form VentanaComplex
     */
    public VentanaComplex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblRes = new javax.swing.JLabel();
        txtAR = new javax.swing.JTextField();
        txtAi = new javax.swing.JTextField();
        txtBR = new javax.swing.JTextField();
        txtBi = new javax.swing.JTextField();
        txtRr = new javax.swing.JTextField();
        txtRi = new javax.swing.JTextField();
        cmbOP = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblA.setText("Complejo A");

        lblB.setText("Complejo B");

        lblRes.setText("Resultado");

        txtAi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAiActionPerformed(evt);
            }
        });

        txtBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBRActionPerformed(evt);
            }
        });

        txtRr.setEditable(false);

        txtRi.setEditable(false);
        txtRi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRiActionPerformed(evt);
            }
        });

        cmbOP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   +", "   -", "   /", "   *" }));
        cmbOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbOPMouseClicked(evt);
            }
        });
        cmbOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOPActionPerformed(evt);
            }
        });

        jLabel4.setText("i");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblB)
                            .addComponent(lblRes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRr, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(txtBR))
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAR, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRi, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(txtBi)
                    .addComponent(txtAi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtRr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblA)
                            .addComponent(txtAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblB)
                            .addComponent(txtBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblRes)))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBRActionPerformed

    private void txtAiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAiActionPerformed

    private void txtRiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRiActionPerformed

    private void cmbOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOPActionPerformed
        operacion();
        
    }//GEN-LAST:event_cmbOPActionPerformed

    private void cmbOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbOPMouseClicked
        operacion();
    }//GEN-LAST:event_cmbOPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaComplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaComplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaComplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaComplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaComplex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOP;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblRes;
    private javax.swing.JTextField txtAR;
    private javax.swing.JTextField txtAi;
    private javax.swing.JTextField txtBR;
    private javax.swing.JTextField txtBi;
    private javax.swing.JTextField txtRi;
    private javax.swing.JTextField txtRr;
    // End of variables declaration//GEN-END:variables

    private void operacion() {
       float ar,ai,br,bi;
       ar=ai=br=bi=0;
        try {
            ar=Float.parseFloat(txtAR.getText());
        } catch (NumberFormatException e) {
            showMessageDialog(this, "Solo Numeros");
            txtAR.setText("");
            txtAR.requestFocus();
        }
        try {
            ai=Float.parseFloat(txtAi.getText());
        } catch (NumberFormatException e) {
            showMessageDialog(this, "Solo Numeros");
            txtAi.setText("");
            txtAi.requestFocus();
        }
        try {
            br=Float.parseFloat(txtBR.getText());
        } catch (NumberFormatException e) {
            showMessageDialog(this, "Solo Numeros");
            txtBR.setText("");
            txtBR.requestFocus();
        }
        try {
            bi=Float.parseFloat(txtBi.getText());
        } catch (NumberFormatException e) {
            showMessageDialog(this, "Solo Numeros");
            txtBi.setText("");
            txtBi.requestFocus();
        }
        Complejo a=new Complejo(ar,ai,1);
        Complejo b=new Complejo(br,bi,1);
        Complejo c=new Complejo();
        switch(cmbOP.getSelectedIndex()){
            case 0:c=a.mas(b);
            break;
            case 1:c=a.menos(b);
            break;
            case 2:c=a.division(b);
            break;
        }
        txtRr.setText(c.getR()+"");
        txtRi.setText(c.getI()+"");
        
       
       
    }
}
