/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FluData;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jmanu
 */
public class Ventdata extends javax.swing.JFrame {

    /**
     * Creates new form Ventdata
     */
    public Ventdata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuOp = new javax.swing.JMenuItem();
        mnuSa = new javax.swing.JMenuItem();
        mnuEx = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        flucatOpen = new javax.swing.JMenuItem();
        flucatSave = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mnuOp.setText("Open");
        mnuOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpActionPerformed(evt);
            }
        });
        jMenu1.add(mnuOp);

        mnuSa.setText("Save");
        mnuSa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSa);

        mnuEx.setText("Exit");
        mnuEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEx);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("FluCat");

        flucatOpen.setText("Open");
        flucatOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flucatOpenActionPerformed(evt);
            }
        });
        jMenu2.add(flucatOpen);

        flucatSave.setText("Save");
        flucatSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flucatSaveActionPerformed(evt);
            }
        });
        jMenu2.add(flucatSave);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpActionPerformed
        // TODO add your handling code here:
        try {
            FileInputStream fl=new FileInputStream("Archivo.txt");
            int c;String cad="";
            while ((c=fl.read())!=-1) {
               
                cad=cad+(char)c;
            }
            txtArea.setText(cad);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ventdata.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Ventdata.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mnuOpActionPerformed

    private void mnuExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_mnuExActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mnuSaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSaActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            java.io.FileOutputStream fs=new java.io.FileOutputStream("Archivo.txt");
            byte b[]=txtArea.getText().getBytes();
            fs.write(b);
            fs.flush();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ventdata.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } catch (IOException ex) {
            Logger.getLogger(Ventdata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuSaActionPerformed

    private void flucatSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flucatSaveActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            java.io.FileWriter fs=new java.io.FileWriter("Archivo");           
            fs.write(txtArea.getText());
            fs.flush();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ventdata.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } catch (IOException ex) {
            Logger.getLogger(Ventdata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_flucatSaveActionPerformed

    private void flucatOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flucatOpenActionPerformed
        // TODO add your handling code here:
        try {
            FileReader fl=new FileReader("Archivo.txt");
            int c;String cad="";
            while ((c=fl.read())!=-1) {
               
                cad=cad+(char)c;
            }
            txtArea.setText(cad);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ventdata.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Ventdata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_flucatOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem flucatOpen;
    private javax.swing.JMenuItem flucatSave;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuEx;
    private javax.swing.JMenuItem mnuOp;
    private javax.swing.JMenuItem mnuSa;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
